### ISSUE TITLE
ImportError: cannot import name '_C' from 'maskrcnn_benchmark' (./AIParsing-main/maskrcnn_benchmark/__init__.py)

### ISSUE THREAD

**Issue by DD20-dai** [31sy/AIParsing#1]
Hello, nice work! When I run python -u test_net_parsing.py --config-file "configs/CIHP/CIHP_AIParsing_R50_75epoch_serialGE_parsingiou_iouloss.yaml" TEST.IMS_PER_BATCH 1 MODEL.WEIGHT ./checkpoints/CIHP_R50_75epoch/model_final.pth 
But I have encountered some problems, I have found a lot of solutions and have not solved it. Have you encountered this problem?

Traceback (most recent call last):
  File "test_net_parsing.py", line 11, in <module>
    from maskrcnn_benchmark.data import make_data_loader
  File "/home/AIParsing-main/maskrcnn_benchmark/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "/home/AIParsing-main/maskrcnn_benchmark/data/build.py", line 10, in <module>
    from . import datasets as D
  File "/home/AIParsing-main/maskrcnn_benchmark/data/datasets/__init__.py", line 2, in <module>
    from .coco import COCODataset
  File "/home/AIParsing-main/maskrcnn_benchmark/data/datasets/coco.py", line 13, in <module>
    from maskrcnn_benchmark.structures.segmentation_mask import SegmentationMask
  File "/home/AIParsing-main/maskrcnn_benchmark/structures/segmentation_mask.py", line 5, in <module>
    from maskrcnn_benchmark.layers.misc import interpolate
  File "/home/AIParsing-main/maskrcnn_benchmark/layers/__init__.py", line 10, in <module>
    from .nms import nms, ml_nms
  File "/home/IParsing-main/maskrcnn_benchmark/layers/nms.py", line 3, in <module>
    from maskrcnn_benchmark import _C
ImportError: cannot import name '_C' from 'maskrcnn_benchmark' (/home/AIParsing-main/maskrcnn_benchmark/__init__.py)

**Comment by Leonora-xy** [comment]
I also encountered this problem. Could you please tell me how it was solved
